#!/usr/bin/perl -w

use strict;

sub gen {
    my ($dir,$opt,$link)=@_;
    mkdir $dir;
    my $file= "$dir/Makefile";
    open my $out, ">", $file
      or die "'$file': $!";
    print $out qq{
CC=gcc
CFLAGS=}.$opt.q{-Wall -Wvector-operation-performance -g -pthread -fopenmp `pkg-config --cflags gtk+-2.0`
LDFLAGS=`pkg-config --libs gtk+-2.0` -lrt -lgomp }.$link.q{
VPATH=..
#LD=gcc  hm how to specify cc for linking?

objects= nstime.o mandelbrot.o main.o


all: main


nstime.o: nstime.c nstime.h Makefile

mandelbrot.o: mandelbrot.c mandelbrot.h nstime.h util.h x_posix_memalign.h Makefile

main.o: main.c mandelbrot.h Makefile


main: $(objects)
	cc -o main $(objects) $(LDFLAGS)

run: main
	bash -c 'time ./main'

gdb: main
	gdb ./main


.PHONY: clean
clean:
	rm -f main $(objects)

} or die $!;
    close $out or die $!;
}

(@ARGV>=2 and @ARGV <= 3) or die "usage: $0 dirpath optstr [linkstr]";

gen(@ARGV);
