main: main.c
	gcc -Wall -g -o main main.c `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`

opt:
	gcc -Wall -g -O3 -o main main.c `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
